#!/usr/bin/env bash
set -euo pipefail

usage() {
cat <<'EOF'
Build a targeted NCBI/minitax genome DB from a list of Kraken2 taxids.

Input:
  A file with NCBI taxids, one per line. These can be species taxids or
  strain/subspecies taxids that can be resolved upward to species.

Output:
  target_selection/selected_accessions.txt
  target_selection/selected_assemblies.tsv
  target_selection/resolved_taxids.tsv
  target_selection/missing_species_taxids.tsv
  plus a full minitax DB generated by scripts/build_ncbi_minitax_db.sh

Usage:
  scripts/build_taxid_targeted_minitax_db.sh \
    --taxids FILE \
    --outdir DIR \
    --per-species 5 \
    --threads 32

Options:
  --taxids FILE              NCBI taxids from Kraken2/unmapped reads. Required.
  --outdir DIR               Output DB directory. Required.
  --per-species N            Number of genomes to keep per species. Default: 5.
  --sources LIST             refseq or refseq,genbank. Default: refseq.
  --tax-groups LIST          NCBI groups. Default: bacteria,archaea.
  --assembly-levels LIST     Default: Complete Genome,Chromosome,Scaffold,Contig.
  --refseq-categories LIST   Default: any.
                             Recommended for targeted rescue: any.
                             Stricter option: reference genome,representative genome.
  --threads N                Threads for minimap2 indexing. Default: 8.
  --index-batch-size SIZE    minimap2 -I size. Default: 128G.
  --max-total N              Optional maximum total selected assemblies.
  --skip-index               Do not build minimap2 index.
  --dry-run                  Select accessions but do not download genomes/build DB.
  --force                    Force rebuild in build_ncbi_minitax_db.sh.
  -h, --help                 Show this help.

Example from a Kraken2 report:
  awk '$4 == "S" {print $5}' unmapped.kraken2.report | sort -u > unmapped_species_taxids.txt

  scripts/build_taxid_targeted_minitax_db.sh \
    --taxids unmapped_species_taxids.txt \
    --outdir /mnt/d/data/databases/canine_unmapped_refseq_targeted \
    --per-species 10 \
    --sources refseq,genbank \
    --threads 32
EOF
}

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

have() {
  command -v "$1" >/dev/null 2>&1
}

download_file() {
  local url="$1"
  local dest="$2"

  if [[ -s "$dest" ]]; then
    echo "[INFO] Using existing: $dest" >&2
    return 0
  fi

  echo "[INFO] Downloading: $url" >&2
  if have curl; then
    curl -L --fail --retry 5 --retry-delay 5 -o "$dest" "$url"
  elif have wget; then
    wget -O "$dest" "$url"
  else
    fail "Need curl or wget."
  fi
}

csv_trim_lines() {
  printf '%s' "$1" | awk -v RS=',' '{gsub(/^[ \t]+|[ \t]+$/, ""); if ($0 != "") print}'
}

TAXIDS=""
OUTDIR=""
PER_SPECIES=5
SOURCES="refseq"
TAX_GROUPS="bacteria,archaea"
ASSEMBLY_LEVELS="Complete Genome,Chromosome,Scaffold,Contig"
REFSEQ_CATEGORIES="any"
THREADS=8
INDEX_BATCH_SIZE="128G"
MAX_TOTAL=""
SKIP_INDEX=0
DRY_RUN=0
FORCE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --taxids) TAXIDS="${2:-}"; shift 2 ;;
    --outdir) OUTDIR="${2:-}"; shift 2 ;;
    --per-species) PER_SPECIES="${2:-}"; shift 2 ;;
    --sources) SOURCES="${2:-}"; shift 2 ;;
    --tax-groups) TAX_GROUPS="${2:-}"; shift 2 ;;
    --assembly-levels) ASSEMBLY_LEVELS="${2:-}"; shift 2 ;;
    --refseq-categories) REFSEQ_CATEGORIES="${2:-}"; shift 2 ;;
    --threads) THREADS="${2:-}"; shift 2 ;;
    --index-batch-size) INDEX_BATCH_SIZE="${2:-}"; shift 2 ;;
    --max-total) MAX_TOTAL="${2:-}"; shift 2 ;;
    --skip-index) SKIP_INDEX=1; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    --force) FORCE=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) fail "Unknown argument: $1" ;;
  esac
done

[[ -n "$TAXIDS" ]] || { usage; fail "--taxids is required."; }
[[ -f "$TAXIDS" ]] || fail "Taxid file not found: $TAXIDS"
[[ -n "$OUTDIR" ]] || { usage; fail "--outdir is required."; }
[[ "$PER_SPECIES" =~ ^[0-9]+$ ]] || fail "--per-species must be an integer."
[[ "$PER_SPECIES" -gt 0 ]] || fail "--per-species must be > 0."
[[ "$THREADS" =~ ^[0-9]+$ ]] || fail "--threads must be an integer."
[[ "$THREADS" -gt 0 ]] || fail "--threads must be > 0."
[[ "$INDEX_BATCH_SIZE" =~ ^[0-9]+[KkMmGgTt]?$ ]] || fail "--index-batch-size must look like 128G, 64000M, or 500000000."

if [[ -n "$MAX_TOTAL" && ! "$MAX_TOTAL" =~ ^[0-9]+$ ]]; then
  fail "--max-total must be an integer."
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILDER="${SCRIPT_DIR}/build_ncbi_minitax_db.sh"
[[ -f "$BUILDER" ]] || fail "Cannot find builder: $BUILDER"

PYTHON_BIN="${PYTHON:-}"
if [[ -z "$PYTHON_BIN" ]]; then
  PYTHON_BIN="$(command -v python3 || command -v python || true)"
fi
[[ -n "$PYTHON_BIN" ]] || fail "No python/python3 found."

mkdir -p "$OUTDIR"/target_selection
SEL_DIR="${OUTDIR}/target_selection"

TAXDUMP="${SEL_DIR}/taxdump.tar.gz"
NODES="${SEL_DIR}/nodes.dmp"
NAMES="${SEL_DIR}/names.dmp"
ALL_ASSEMBLIES="${SEL_DIR}/assembly_summary.target_sources.tsv"
SELECTED="${SEL_DIR}/selected_assemblies.tsv"
ACCESSIONS="${SEL_DIR}/selected_accessions.txt"
RESOLVED="${SEL_DIR}/resolved_taxids.tsv"
MISSING="${SEL_DIR}/missing_species_taxids.tsv"

echo "[INFO] Output directory: $OUTDIR"
echo "[INFO] Taxids: $TAXIDS"
echo "[INFO] Representatives per species: $PER_SPECIES"
echo "[INFO] Sources: $SOURCES"
echo "[INFO] Tax groups: $TAX_GROUPS"
echo "[INFO] Assembly levels: $ASSEMBLY_LEVELS"
echo "[INFO] RefSeq categories: $REFSEQ_CATEGORIES"

download_file "https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz" "$TAXDUMP"
if [[ ! -s "$NODES" || ! -s "$NAMES" ]]; then
  tar -xzf "$TAXDUMP" -C "$SEL_DIR" nodes.dmp names.dmp
fi

{
  printf 'assembly_accession\trefseq_category\ttaxid\tspecies_taxid\torganism_name\tinfraspecific_name\tisolate\tversion_status\tassembly_level\tftp_path\tsource\ttax_group\tgenome_size\n'

  while read -r source; do
    [[ -n "$source" ]] || continue
    [[ "$source" == "refseq" || "$source" == "genbank" ]] || fail "Unsupported source: $source. Use refseq or refseq,genbank."

    while read -r group; do
      [[ -n "$group" ]] || continue

      summary="${SEL_DIR}/assembly_summary_${source}_${group}.txt"
      url="https://ftp.ncbi.nlm.nih.gov/genomes/${source}/${group}/assembly_summary.txt"
      download_file "$url" "$summary" >&2

      awk -F '\t' -v OFS='\t' -v src="$source" -v grp="$group" '
        $0 !~ /^#/ && NF >= 20 {
          # assembly_summary columns:
          # 1 assembly_accession; 5 refseq_category; 6 taxid; 7 species_taxid
          # 8 organism_name; 9 infraspecific_name; 10 isolate; 11 version_status
          # 12 assembly_level; 20 ftp_path; 26 genome_size
          print $1, $5, $6, $7, $8, $9, $10, $11, $12, $20, src, grp, $26
        }
      ' "$summary"

    done < <(csv_trim_lines "$TAX_GROUPS")

  done < <(csv_trim_lines "$SOURCES")
} > "$ALL_ASSEMBLIES"

"$PYTHON_BIN" - "$TAXIDS" "$NODES" "$NAMES" "$ALL_ASSEMBLIES" "$SELECTED" "$ACCESSIONS" "$RESOLVED" "$MISSING" "$PER_SPECIES" "$ASSEMBLY_LEVELS" "$REFSEQ_CATEGORIES" "${MAX_TOTAL:-}" <<'PY'
import sys
import csv
from collections import defaultdict

taxids_file, nodes_file, names_file, assemblies_file, selected_file, accessions_file, resolved_file, missing_file, per_species, assembly_levels, refseq_categories, max_total = sys.argv[1:13]
per_species = int(per_species)
max_total = int(max_total) if max_total else None

allowed_levels = [x.strip() for x in assembly_levels.split(",") if x.strip()]
allowed_level_set = set(allowed_levels)

category_any = refseq_categories.strip().lower() == "any"
allowed_categories = set([x.strip() for x in refseq_categories.split(",") if x.strip()])

level_priority = {
    "Complete Genome": 0,
    "Chromosome": 1,
    "Scaffold": 2,
    "Contig": 3,
}

category_priority = {
    "reference genome": 0,
    "representative genome": 1,
    "na": 2,
    "": 3,
}

source_priority = {
    "refseq": 0,
    "genbank": 1,
}

parent = {}
rank = {}

with open(nodes_file) as f:
    for line in f:
        parts = [x.strip() for x in line.split("|")]
        if len(parts) >= 3:
            taxid, parent_taxid, r = parts[0], parts[1], parts[2]
            parent[taxid] = parent_taxid
            rank[taxid] = r

names = {}
with open(names_file) as f:
    for line in f:
        parts = [x.strip() for x in line.split("|")]
        if len(parts) >= 4 and parts[3] == "scientific name":
            names[parts[0]] = parts[1]

def read_taxids(path):
    vals = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            vals.append(line.split()[0])
    return vals

def to_species_taxid(taxid):
    cur = str(taxid)
    seen = set()

    while cur and cur not in seen:
        seen.add(cur)

        if rank.get(cur) == "species":
            return cur

        par = parent.get(cur)
        if not par or par == cur:
            return None

        cur = par

    return None

input_taxids = read_taxids(taxids_file)

resolved_rows = []
target_species = set()
unresolved = []

for t in input_taxids:
    sp = to_species_taxid(t)
    if sp is None:
        unresolved.append(t)
        resolved_rows.append((t, "", "", "unresolved_no_species_ancestor"))
    else:
        target_species.add(sp)
        resolved_rows.append((t, sp, names.get(sp, ""), "resolved"))

with open(resolved_file, "w") as out:
    out.write("input_taxid\tspecies_taxid\tspecies_name\tstatus\n")
    for row in resolved_rows:
        out.write("\t".join(row) + "\n")

by_species = defaultdict(list)

with open(assemblies_file) as f:
    reader = csv.DictReader(f, delimiter="\t")
    for row in reader:
        acc = row.get("assembly_accession", "")
        taxid = row.get("taxid", "")
        species_taxid = row.get("species_taxid", "")
        ftp_path = row.get("ftp_path", "")
        version_status = row.get("version_status", "")
        assembly_level = row.get("assembly_level", "")
        refseq_category = row.get("refseq_category", "")
        source = row.get("source", "")
        genome_size = row.get("genome_size", "")

        if not acc or not ftp_path or ftp_path == "na":
            continue

        if version_status and version_status != "latest":
            continue

        if species_taxid not in target_species and taxid not in target_species:
            continue

        if assembly_level not in allowed_level_set:
            continue

        if not category_any:
            if refseq_category not in allowed_categories:
                if not (row.get("tax_group", "") == "viral" and refseq_category == "na"):
                    continue

        key_species = species_taxid if species_taxid in target_species else taxid

        try:
            gsize = int(genome_size)
        except Exception:
            gsize = 0

        row["_sort_key"] = (
            source_priority.get(source, 9),
            category_priority.get(refseq_category, 9),
            level_priority.get(assembly_level, 9),
            -gsize,
            acc,
        )

        by_species[key_species].append(row)

selected = []
missing_species = []

for sp in sorted(target_species, key=lambda x: int(x) if x.isdigit() else x):
    rows = by_species.get(sp, [])
    if not rows:
        missing_species.append(sp)
        continue

    rows = sorted(rows, key=lambda r: r["_sort_key"])
    selected.extend(rows[:per_species])

if max_total is not None:
    selected = selected[:max_total]

fieldnames = [
    "assembly_accession",
    "refseq_category",
    "taxid",
    "species_taxid",
    "organism_name",
    "infraspecific_name",
    "isolate",
    "version_status",
    "assembly_level",
    "ftp_path",
    "source",
    "tax_group",
    "genome_size",
]

with open(selected_file, "w", newline="") if sys.version_info[0] >= 3 else open(selected_file, "w") as out:
    writer = csv.DictWriter(out, delimiter="\t", fieldnames=fieldnames, extrasaction="ignore")
    writer.writeheader()
    for row in selected:
        writer.writerow(row)

with open(accessions_file, "w") as out:
    for row in selected:
        out.write(row["assembly_accession"] + "\n")

with open(missing_file, "w") as out:
    out.write("species_taxid\tspecies_name\n")
    for sp in missing_species:
        out.write("%s\t%s\n" % (sp, names.get(sp, "")))

print("[INFO] Input taxids: %d" % len(input_taxids))
print("[INFO] Resolved target species: %d" % len(target_species))
print("[INFO] Unresolved input taxids: %d" % len(unresolved))
print("[INFO] Selected assemblies: %d" % len(selected))
print("[INFO] Species without assemblies after filters: %d" % len(missing_species))
print("[INFO] Selected accessions: %s" % accessions_file)
PY

selected_count="$(wc -l < "$ACCESSIONS" | awk '{print $1}')"
echo "[INFO] Selected accession count: $selected_count"

if [[ "$selected_count" -eq 0 ]]; then
  fail "No assemblies selected. Try --sources refseq,genbank and/or --refseq-categories any and/or relaxed --assembly-levels."
fi

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "[INFO] Dry run complete."
  echo "[INFO] Selected assemblies: $SELECTED"
  echo "[INFO] Selected accessions: $ACCESSIONS"
  echo "[INFO] Missing species: $MISSING"
  exit 0
fi

BUILDER_ARGS=(
  --outdir "$OUTDIR"
  --sources "$SOURCES"
  --tax-groups "$TAX_GROUPS"
  --assembly-levels "$ASSEMBLY_LEVELS"
  --refseq-categories "$REFSEQ_CATEGORIES"
  --assembly-accessions "$ACCESSIONS"
  --threads "$THREADS"
  --index-batch-size "$INDEX_BATCH_SIZE"
)

if [[ "$SKIP_INDEX" -eq 1 ]]; then
  BUILDER_ARGS+=(--skip-index)
fi

if [[ "$FORCE" -eq 1 ]]; then
  BUILDER_ARGS+=(--force)
fi

echo "[INFO] Calling minitax NCBI DB builder:"
printf '  %q' "$BUILDER" "${BUILDER_ARGS[@]}"
echo

"$BUILDER" "${BUILDER_ARGS[@]}"

echo "[DONE]"
echo "Resolved taxids:       $RESOLVED"
echo "Selected assemblies:   $SELECTED"
echo "Selected accessions:   $ACCESSIONS"
echo "Missing species:       $MISSING"
echo "Minitax DB directory:  $OUTDIR"
